# Generated by Django 5.0.6 on 2024-07-05 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geolocation", "0004_delete_location_student_city_student_country_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Universite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("adresse", models.CharField(max_length=255)),
                ("ville", models.CharField(blank=True, max_length=100, null=True)),
                ("code_postal", models.CharField(blank=True, max_length=20, null=True)),
                ("pays", models.CharField(blank=True, max_length=100, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Etudiant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prenom", models.CharField(max_length=100)),
                ("nom", models.CharField(max_length=100)),
                ("adresse", models.CharField(max_length=255)),
                ("ville", models.CharField(blank=True, max_length=100, null=True)),
                ("code_postal", models.CharField(blank=True, max_length=20, null=True)),
                ("pays", models.CharField(blank=True, max_length=100, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "universite",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="geolocation.universite",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Student",
        ),
        migrations.DeleteModel(
            name="University",
        ),
    ]
