# Generated by Django 5.0.6 on 2024-07-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geolocation", "0006_remove_etudiant_adresse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etudiant",
            name="code_postal",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="etudiant",
            name="pays",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="etudiant",
            name="ville",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="universite",
            name="code_postal",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="universite",
            name="pays",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="universite",
            name="ville",
            field=models.CharField(max_length=100),
        ),
    ]
